# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='karma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
