# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0004_auto_20160324_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(upload_to='Images/users', verbose_name='Image'),
        ),
    ]
