# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0005_auto_20160324_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
