# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0008_auto_20160324_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(to='hat.UserProfile'),
        ),
    ]
