# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0010_game_secret_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.CharField(default='test', max_length=63),
        ),
    ]
