# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 17:11
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0011_room_title'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='room',
            managers=[
                ('room', django.db.models.manager.Manager()),
            ],
        ),
    ]
