# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0013_auto_20160324_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.CharField(default='test', max_length=63),
        ),
    ]
