# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0014_game_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(choices=[('PL', 'Player'), ('Ld', 'Leader')], max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hat.Game')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hat.UserProfile')),
            ],
        ),
        migrations.RenameModel(
            old_name='Secret_word',
            new_name='SecretWord',
        ),
        migrations.RemoveField(
            model_name='user_role',
            name='game',
        ),
        migrations.RemoveField(
            model_name='user_role',
            name='users',
        ),
        migrations.AlterField(
            model_name='message',
            name='user_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hat.UserGame'),
        ),
        migrations.DeleteModel(
            name='User_Role',
        ),
    ]
