# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0015_auto_20160324_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergame',
            old_name='users',
            new_name='user',
        ),
    ]
