# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0016_auto_20160324_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='user_role',
            field=models.CharField(choices=[('PL', 'Player'), ('Ld', 'Leader')], default=('PL', 'Player'), max_length=255),
        ),
    ]
