# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0018_auto_20160325_0122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergame',
            options={'verbose_name': 'UserGame'},
        ),
    ]
