# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0020_remove_like_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time_creation',
            field=models.DateTimeField(verbose_name='\u0412\u0440\u0435\u043c\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
        ),
    ]
