# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0021_auto_20160331_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='user_role',
            field=models.CharField(choices=[('Player', 'Player'), ('Leader', 'Leader')], default=('Player', 'Player'), max_length=255),
        ),
    ]
