# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0024_auto_20160331_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergame',
            name='user_role',
        ),
    ]
