# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0025_remove_usergame_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergame',
            name='user_role',
            field=models.CharField(choices=[('Player', 'Player'), ('Leader', 'Leader')], default=('Player', 'Player'), max_length=255),
        ),
    ]
