# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0027_auto_20160331_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='usergame',
            name='game',
        ),
        migrations.RemoveField(
            model_name='usergame',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user_role',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='UserGame',
        ),
    ]
