# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0034_message_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hat.UserRole'),
        ),
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(default=1, to='hat.UserProfile'),
        ),
    ]
