# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0035_auto_20160510_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(to='hat.UserProfile'),
        ),
    ]
