# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0039_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='HelloTest',
        ),
    ]
