# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0040_auto_20160512_1636'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelloTest',
        ),
    ]
