# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hat', '0041_delete_hellotest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time_creation',
            field=models.DateTimeField(verbose_name='Time of creation'),
        ),
    ]
